### ISSUE TITLE
搜索题目时分词有没有必要

### ISSUE THREAD

**Issue by jossion12** [qishibo/totop#15]
可以考虑分词后用+号关联词，再搜索，但要根据关联度过滤掉不相干的词
http://120.26.6.172/get.php?source=%E4%BC%A0%E7%BB%9F%E4%BA%8C%E5%8D%81%E5%9B%9B%E8%8A%82%E6%B0%94%E4%B8%AD%EF%BC%8C%E6%9C%80%E6%97%A9%E8%A2%AB%E5%88%B6%E5%AE%9A%E5%87%BA%E6%9D%A5%E7%9A%84%E6%98%AF%E5%93%AA%E4%B8%80%E4%B8%AA%EF%BC%9F&param1=0&param2=1
参照这个，自己试着改了下，但遇到一些特殊题时，效果不理想

**Comment by qishibo** [comment]
哈哈 一开始也想着切词来的，但复杂性有点高，如果是典型的主谓宾或者其他句型效果还可以，但稍复杂的问题效果就差多了

之前用的是百度切词服务，你这个哪里的

**Comment by jossion12** [comment]
網上找的，http://pullword.com/
